server:
  port: 1010

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/paperRoll/cloud-config.git
          clone-on-start: true
          skip-ssl-validation: true